### ISSUE TITLE
Download quality

### ISSUE THREAD

**Issue by rockstar2020** [xHossein/radiojavanapi#1]
Hi there, 
First of all great work on wrapping this API.
It works seamlessly!
I was wondering why the maximum download quality you provide in this API is 256kbps.

Other RJ downloaders out there provide a download link for 320kbps quality.

Hoping you could add this feature. 

Thanks

**Comment by xHossein** [comment]
This is the exact results of RJ API, usually it returns 256 kbps for 'hq_link', 'link' and...
Also sometime it returns 192 kbps as HQ link.

I noticed even when 320 kbps exists, RJ API returns 256 kbps. You can get highest quality by replacing '256' to '320' in the download link.

The next update will include this.

**Comment by rockstar2020** [comment]
Thanks. 
Also FYI as an alternative I'm reconstructing the URL and am able to download the 320kpbs version from: 
https://host2.rj-mw1.com/media/mp3/{artist}{title}.mp3

Of course all spaces need to be replaced with '-'.
I'm closing this issue for now. 
Thanks
