### ISSUE TITLE
help

### ISSUE THREAD

**Issue by javadmahmoodi670** [xHossein/radiojavanapi#2]
سلام
ایا میشه موزیک رو دانلود کرد؟ و اینکه اگه میشه کدوم قسمت لینک موزیک رو باید بدیم به کدمون؟
منظورم اینکه چجوری لینک موزیک رو از سایت رادیو جوان بگیریم!!

**Comment by xHossein** [comment]
Use `get_song_by_url()` or `get_song_by_id()` to get song info, which contains dl links.
Read [Doc](https://xhossein.github.io/radiojavanapi/#/methods?id=song).
